language: php
php:
- hhvm
sudo: false
cache:
  directories:
  - $HOME/.composer/cache
branches:
  only:
  - source
before_install:
- echo -e "machine github.com\n  login $GH_TOKEN" >> ~/.netrc
before_script:
- gem install sass
- composer selfupdate
- composer install --prefer-dist
script:
- sh build.sh
after_success:
- if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then sh publish.sh; fi
env:
  global:
    secure: m2tbZQYhWBfZKoJ8qO3cETr67ZOpVqGcFbNaYcyv53gxBUS26KVIQaFWyGegdv0tnl4tOyNOaXtOcLP2izc1rauHU8hv+9mUwDHA3wyRk4ao0KLB362OFEvkyAabBWi8vnEM1o66ZS+o/dUNyNRXl+xLeKgJXiaH64yEYpI8l7Q=
