language: php
php:
- hhvm
sudo: false
cache:
  directories:
  - $HOME/.composer/cache
branches:
  only:
  - source
before_install:
- echo -e "machine github.com\n  login $GH_TOKEN" >> ~/.netrc
before_script:
- gem install sass
- composer selfupdate
- composer install --prefer-dist
script:
- sh build.sh
after_success:
- if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then sh publish.sh; fi
env:
  global:
    secure: "qZvPiv5ZnK8uVesv05bo+BaUr0DhH+Sb0mBtWr/tS+ohp4fg7BQx4abXFe9out0GFxBaAxy4J2obd4TNLkSM6me8mwMxmrVRAGZXvHRh04fIO0LpVhoeRgAAcRGHCbqAvk40mNCEgUMU7X/nKLDHrLcgZlyRdTTmWWcrgSpfitY="
