language: php
php: 7

sudo: false

branches:
  only:
  - source

before_install:
  - phpenv config-rm xdebug.ini || true
  - composer selfupdate
  - echo -e "machine github.com\n  login $GH_TOKEN" >> ~/.netrc

install: composer install --prefer-dist

script: sh build.sh

after_success: if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then sh publish.sh; fi

env:
  global:
    secure: WfXSxh84A+qtGWRVNIvWssaqIla8pOcNTjycPsIRLJgiiaVmJN3E7Acxe2/++lC9w5D9MKpoZpdyfXmsjvN2QpTbGb0yupZ7FKtZZpomYyFGQnkwiU3wsDQNikjsvYE2Gr25MKzZ0phhj0lmOGV1jXgXgQ0/GDz9B/6nzDBki8Q=
