language: php
php: 7.1
sudo: false
cache:
  directories:
    - $HOME/.composer/cache/files
branches:
  only:
  - source
before_install:
  - phpenv config-rm xdebug.ini
  - echo -e "machine github.com\n  login $GH_TOKEN" >> ~/.netrc
install: composer install --prefer-dist
script: sh build.sh
after_success: if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then sh publish.sh; fi
env:
  global:
    secure: Osxth0l1MxNmxS1Uxgia9Inh9CXexw9r3D4CPwIyswJkcQTFpNUdXPk5hOuAVym+YibEYtX3yLjrLs6u0wZP7B/XoWoTpr7RnXCL5x1zxAanWWha5E0I1ghm2izjFg00ADt1rGeoajKt12t+PqBemycx+3bu792vGd9aF6InwF4=
